# -*- coding: utf-8 -*-
db=DB()
db('Paginas').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db.load=True
db('Paginas').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Paginas').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Paginas').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Paginas').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Entradas').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Entradas').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Entradas').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Entradas').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Entradas').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Categorias').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Categorias').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Categorias').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Categorias').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Categorias').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Pagina-0').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Pagina-0').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Pagina-0').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Pagina-0').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Pagina-0').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Builder').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Builder').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Builder').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Builder').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Builder').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Pagina-0').insertar('Inicio', [[{'Titulo': 'text', 'name': 'titulo', 'value': 'Inicio'}, {'Secci\xc3\xb3n': 'text-titulo', 'name': 'section-header', 'value': 'Home4'}, {'opcion': 0, 'Logo': 'select', 'opciones': 'archivos', 'name': 'logo', 'value': 0}, {'Conenido': 'textarea', 'value': '', 'name': 'contenido'}], [{'Secci\xc3\xb3n': 'text-titulo', 'name': 'section-about', 'value': 'About Us'}]], {'Pagina-0': 0}, '8/8/2017 19:45:34', [])
db('Paginas').insertar('Inicio12', [[{'Titulo': 'text', 'name': 'titulo', 'value': 'Inicio12'}, {'Plantilla': 'hidden', 'name': 'plantilla', 'value': 'index'}, {'Secci\xc3\xb3n': 'text-titulo', 'name': 'section-header', 'value': 'Home4'}, {'opcion': 0, 'Logo': 'select', 'opciones': 'archivos', 'name': 'logo', 'value': 0}, {'Conenido': 'textarea', 'value': '', 'name': 'contenido'}], [{'Secci\xc3\xb3n': 'text-titulo', 'name': 'section-about', 'value': 'About Us'}]], {'Pagina': 0}, '28/1/2018 15:38:7', [{'name': 'atributo-layout', 'value': None}, {'name': 'atributo-control', 'value': None}])
db('Builder').insertar('Inicio', [], {'Builder': 0}, '8/8/2017 19:45:34', [])
db.load=False
